import random

COUNTRY_CODES = {
    # Asia
    "Afganistán": "1",
    "Baréin": "2",
    "Bangladesh": "3",
    "Bután": "4",
    "Brunéi": "5",
    "Camboya": "6",
    "China": "7",
    "Hong Kong": "8",
    "India": "9",
    "Indonesia": "10",
    "Irán": "11",
    "Irak": "12",
    "Japón": "13",
    "Jordania": "14",
    "Corea del Norte": "15",
    "Corea del Sur": "16",
    "Kuwait": "17",
    "Laos": "18",
    "Líbano": "19",
    "Macao": "20",
    "Malasia": "21",
    "Maldivas": "22",
    "Mongolia": "23",
    "Myanmar": "24",
    "Nepal": "25",
    "Omán": "26",
    "Pakistán": "27",
    "Palestina": "28",
    "Filipinas": "29",
    "Catar": "30",
    "Arabia Saudita": "31",
    "Singapur": "32",
    "Sri Lanka": "33",
    "Siria": "34",
    "Tailandia": "36",
    "Emiratos Árabes Unidos": "37",
    "Vietnam": "38",
    "Yemen": "39",
    "Kirguistán": "40",
    "Tayikistán": "41",
    "Turkmenistán": "42",
    "Timor Oriental": "43",

    # África
    "Argelia": "44",
    "Angola": "45",
    "Benín": "46",
    "Botsuana": "47",
    "Burkina Faso": "48",
    "Burundi": "49",
    "Camerún": "50",
    "Cabo Verde": "51",
    "República Centroafricana": "52",
    "Chad": "53",
    "Comoras": "54",
    "República Democrática del Congo": "55",
    "Costa de Marfil": "56",
    "Yibuti": "57",
    "Egipto": "58",
    "Guinea Ecuatorial": "59",
    "Eritrea": "60",
    "Etiopía": "61",
    "Gabón": "62",
    "Gambia": "63",
    "Ghana": "64",
    "Guinea": "65",
    "Guinea-Bisáu": "66",
    "Kenia": "67",
    "Lesoto": "68",
    "Liberia": "69",
    "Libia": "70",
    "Madagascar": "71",
    "Malaui": "72",
    "Malí": "73",
    "Mauritania": "74",
    "Mauricio": "75",
    "Marruecos": "76",
    "Mozambique": "77",
    "Namibia": "78",
    "Níger": "79",
    "Nigeria": "80",
    "Ruanda": "81",
    "Santo Tomé y Príncipe": "82",
    "Senegal": "83",
    "Seychelles": "84",
    "Sierra Leona": "85",
    "Somalia": "86",
    "Sudáfrica": "87",
    "Sudán": "88",
    "Esuatini": "89",
    "Tanzania": "90",
    "Togo": "91",
    "Túnez": "92",
    "Uganda": "93",
    "Zambia": "94",
    "Zimbabue": "95",
    "Congo": "98",
    "Sudán del Sur": "312",

    # América del Norte, Central y Caribe
    "Antigua y Barbuda": "104",
    "Aruba": "105",
    "Bahamas": "106",
    "Barbados": "107",
    "Belice": "108",
    "Bermudas": "109",
    "Canadá": "110",
    "Islas Caimán": "111",
    "Costa Rica": "112",
    "Cuba": "113",
    "Dominica": "114",
    "República Dominicana": "115",
    "El Salvador": "116",
    "Granada": "117",
    "Guatemala": "119",
    "Haití": "120",
    "Honduras": "121",
    "Jamaica": "122",
    "México": "124",
    "Nicaragua": "127",
    "Panamá": "128",
    "Puerto Rico": "129",
    "San Cristóbal y Nieves": "130",
    "Santa Lucía": "131",
    "San Vicente y las Granadinas": "132",
    "Trinidad y Tobago": "133",
    "Islas Turcas y Caicos": "134",
    "Estados Unidos": "135",
    "Islas Vírgenes Británicas": "136",
    "Islas Vírgenes de los EE.UU.": "137",
    "Surinam": "139",
    "Curazao": "140",

    # América del Sur
    "Argentina": "144",
    "Bolivia": "145",
    "Brasil": "146",
    "Chile": "147",
    "Colombia": "148",
    "Ecuador": "149",
    "Paraguay": "150",
    "Perú": "151",
    "Uruguay": "152",
    "Venezuela": "153",
    "Guyana": "159",

    # Oceanía
    "Samoa Americana": "161",
    "Australia": "162",
    "Islas Cook": "163",
    "Fiyi": "164",
    "Nueva Caledonia": "165",
    "Nueva Zelanda": "166",
    "Papúa Nueva Guinea": "167",
    "Samoa": "168",
    "Islas Salomón": "169",
    "Tahití": "170",
    "Tonga": "171",
    "Vanuatu": "172",
    "Guam": "176",
    "Palau": "184",

    # Europa
    "Israel": "189",
    "Turquía": "190",
    "Zerphen": "191",
    "Stralla": "192",
    "Columbiqash": "193",
    "Nardin": "194",
    "New Libertalia Kingdom": "195",
    "Otterland": "196",
    "Nordustra": "197",
    "Furilisca": "198",
    "Jutsa": "199",
    "Realizer": "200",
    "Ruinenlust": "201",
    "República Checa": "202",
    "Einswenn": "203",
    "Cacusia": "204",
    "FO": "205",
    "Bisofeyr": "206",
    "Finlandia": "207",
    "Roless": "208",
    "Georgia": "209",
    "A&K": "210",
    "Grecia": "211",
    "Atsvea": "212",
    "Islandia": "213",
    "UMF": "214",
    "Lumiose": "215",
    "Kazajistán": "216",
    "Letonia": "217",
    "Mozolephies": "218",
    "Lituania": "219",
    "Luxemburgo": "220",
    "Macedonia": "221",
    "Sehir": "222",
    "Moldavia": "223",
    "VH": "224",
    "Irlanda del Norte": "225",
    "Noruega": "226",
    "Polonia": "227",
    "Portugal": "228",
    "Rumanía": "229",
    "Reannia": "230",
    "CTC": "231",
    "Escocia": "232",
    "Eslovaquia": "234",
    "Eslovenia": "235",
    "Bilsa": "236",
    "Suecia": "237",
    "Suiza": "238",
    "Ucrania": "239",
    "Uzbekistán": "240",
    "Gales": "241",
    "Gibraltar": "245",
    "Mónaco": "250",
    "Taiwán": "298",
    "Serbia": "303",
    "Montenegro": "304",
    "Kosovo": "311",
}


FORMATIONS = {
    "4-3-3": {
        "GK": 1,
        "CB": 2,
        "LB": 1,
        "RB": 1,
        "DMF": 1,
        "CMF": 2,
        "LWF": 1,
        "RWF": 1,
        "CF": 1,
    },
    "5-3-2": {
        "GK": 1,
        "CB": 3,
        "LB": 1,
        "RB": 1,
        "CMF": 2,
        "AMF": 1,
        "CF": 2,
    },
    "3-5-2": {
        "GK": 1,
        "CB": 3,
        "LMF": 1,
        "RMF": 1,
        "CMF": 2,
        "AMF": 1,
        "CF": 2,
    },
    "4-4-2": {
        "GK": 1,
        "CB": 2,
        "LB": 1,
        "RB": 1,
        "LMF": 1,
        "RMF": 1,
        "CMF": 2,
        "CF": 2,
    },
    "3-4-3": {
        "GK": 1,
        "CB": 3,
        "LB": 1,
        "RB": 1,
        "CMF": 2,
        "LWF": 1,
        "RWF": 1,
        "CF": 1,
    },
}

TEAM_RATINGS = {
    "amateur": (40, 60),
    "semi_pro": (55, 75),
    "professional": (70, 85),
    "elite": (80, 95),
    "mixed": (50, 99),  # RANDOM
}

def generate_full_squad(squad_size=26, country=None, team_type="professional"):
    from main import PlayerGenerator 
    
    if team_type not in TEAM_RATINGS:
        print(f"ERROR: team_type should be one of {', '.join(TEAM_RATINGS.keys())}")
        return None
    
    generator = PlayerGenerator()
    rating_range = TEAM_RATINGS[team_type]
    
    distribution = {
        "GK": 3,
        "CB": max(4, int(squad_size * 0.17)),
        "LB": max(2, int(squad_size * 0.09)),
        "RB": max(2, int(squad_size * 0.09)),
        "DMF": max(2, int(squad_size * 0.09)),
        "CMF": max(2, int(squad_size * 0.13)),
        "LMF": max(0, int(squad_size * 0.09)),
        "RMF": max(0, int(squad_size * 0.09)),
        "AMF": max(0, int(squad_size * 0.09)),
        "LWF": max(0, int(squad_size * 0.09)),
        "RWF": max(0, int(squad_size * 0.09)),
        "SS": max(0, int(squad_size * 0.09)),
        "CF": max(2, int(squad_size * 0.13)),
    }
    
    total = sum(distribution.values())
    if total != squad_size:
        distribution["CF"] += (squad_size - total)
    
    team = []
    for position, count in distribution.items():
        for _ in range(count):
            kwargs = {"Position": position}
            if country:
                kwargs["Country"] = country
            kwargs["Rating"] = random.randint(rating_range[0], rating_range[1])
            
            team.append(generator.generate_player(**kwargs))
    
    return team